import { type EZPElectronAPI } from '@ezplayer/ezplayer-core';
import { isElectron, ToastMsgs } from '@ezplayer/shared-ui-components';
import {
    Button,
    Divider,
    FormControlLabel,
    Link,
    Radio,
    TextField,
    Typography,
} from '@mui/material';
import { createSelector } from '@reduxjs/toolkit';
import { QRCodeSVG } from 'qrcode.react';
import React, { useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { v4 as uuidv4 } from 'uuid';
import { Box } from '../box/Box';
import { API_ENDPOINTS } from '../../store/api/ApiEndpoints';
import { postSetCloudUrl, postSetPlayerIdToken } from '../../store/slices/AuthStore';
import { issueCloudCommand } from '../../store/slices/CloudStatusStore';
import { CloudPollingEditor } from './CloudPollingEditor';
import type { AppDispatch, RootState } from '../../store/Store';

declare global {
    interface Window {
        electronAPI?: EZPElectronAPI;
    }
}

const selectCloudConfig = (state: RootState) => state.cloudConfig;
const selectCloudStatus = (state: RootState) => state.cloudStatus;
const selectPlayerIdToken = createSelector([selectCloudConfig], (cfg) => cfg.playerIdToken);
const selectCloudServiceUrl = createSelector([selectCloudConfig], (cfg) => cfg.cloudServiceUrl);
const selectIsRegistered = createSelector([selectCloudStatus], (s) => s.playerIdIsRegistered);

interface PlayerCloudRegistrationPanelProps {
    /** Hide the Cloud Service URL editor when true (e.g. inside a Welcome bootstrap
     *  where the URL is implied to be the default). */
    hideCloudUrl?: boolean;
}

/**
 * The body of the player-registration UX, factored out of `PlayerCloudRegistrationDialog`
 * so the same widget can be embedded inline (Welcome bootstrap) and as a modal dialog.
 */
export const PlayerCloudRegistrationPanel: React.FC<PlayerCloudRegistrationPanelProps> = ({
    hideCloudUrl,
}) => {
    const dispatch = useDispatch<AppDispatch>();

    const playerIdToken = useSelector(selectPlayerIdToken);
    const cloudServiceUrl = useSelector(selectCloudServiceUrl);
    const playerIdIsRegistered = useSelector(selectIsRegistered);

    const [cloudUrlInput, setCloudUrlInput] = useState('');
    const [isEditingCloudUrl, setIsEditingCloudUrl] = useState(false);

    const [tempPlayerId, setTempPlayerId] = useState<string>(playerIdToken);
    const [autoGeneratedPlayerId, setAutoGeneratedPlayerId] = useState<string>(playerIdToken);
    const [manualPlayerId, setManualPlayerId] = useState<string>('');
    const [playerIdInputMode, setPlayerIdInputMode] = useState<'auto' | 'manual'>('auto');

    useEffect(() => {
        setTempPlayerId(playerIdToken);
        setAutoGeneratedPlayerId(playerIdToken);
    }, [playerIdToken]);

    useEffect(() => {
        setCloudUrlInput(cloudServiceUrl || '');
    }, [cloudServiceUrl]);

    // Fast-poll while waiting for registration. Default heartbeat is 30 s; that's
    // sluggish for someone watching the QR code. Tick a manual poll every 2 s
    // until the cloud confirms registration, then stop.
    useEffect(() => {
        if (playerIdIsRegistered) return;
        const id = window.setInterval(() => {
            void dispatch(issueCloudCommand({ type: 'pollNow' }));
        }, 2000);
        return () => window.clearInterval(id);
    }, [playerIdIsRegistered, dispatch]);

    const handlePlayerIdModeChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const mode = event.target.value as 'auto' | 'manual';
        setPlayerIdInputMode(mode);
        if (mode === 'auto') {
            setTempPlayerId(autoGeneratedPlayerId);
        } else {
            setTempPlayerId(manualPlayerId);
        }
    };

    const handlePlayerIdInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value;
        setTempPlayerId(value);
        if (playerIdInputMode === 'auto') {
            setAutoGeneratedPlayerId(value);
        } else {
            setManualPlayerId(value);
        }
    };

    const handlePlayerIdBlur = () => {
        if (playerIdInputMode === 'auto') {
            setAutoGeneratedPlayerId(tempPlayerId);
        } else {
            setManualPlayerId(tempPlayerId);
        }
    };

    const handleGeneratePlayerId = () => {
        const newPlayerId = uuidv4();
        setAutoGeneratedPlayerId(newPlayerId);
        setTempPlayerId(newPlayerId);
        setPlayerIdInputMode('auto');

        dispatch(postSetPlayerIdToken({ playerIdToken: newPlayerId }))
            .then(() => {
                ToastMsgs.showSuccessMessage('Player ID generated. Scan the QR code or open the URL to register.', {
                    theme: 'colored',
                    position: 'bottom-right',
                    autoClose: 2000,
                });
            })
            .catch((error) => {
                ToastMsgs.showErrorMessage('Failed to generate player ID', {
                    theme: 'colored',
                    position: 'bottom-right',
                    autoClose: 2000,
                });
                console.error('Error generating player ID:', error);
            });
    };

    const handleClearPlayerId = () => {
        setAutoGeneratedPlayerId('');
        setManualPlayerId('');
        setTempPlayerId('');
        dispatch(postSetPlayerIdToken({ playerIdToken: '' }))
            .then(() => {
                ToastMsgs.showSuccessMessage('Player ID cleared.', {
                    theme: 'colored',
                    position: 'bottom-right',
                    autoClose: 2000,
                });
            })
            .catch((error) => {
                ToastMsgs.showErrorMessage('Failed to clear player ID', {
                    theme: 'colored',
                    position: 'bottom-right',
                    autoClose: 2000,
                });
                console.error('Error clearing player ID:', error);
            });
    };

    const handleApplyManualPlayerId = () => {
        const idToApply = tempPlayerId.trim();
        if (!idToApply) {
            ToastMsgs.showErrorMessage('Please enter a Player ID first', {
                theme: 'colored',
                position: 'bottom-right',
                autoClose: 2000,
            });
            return;
        }
        dispatch(postSetPlayerIdToken({ playerIdToken: idToApply }))
            .then(() => {
                setManualPlayerId(idToApply);
                ToastMsgs.showSuccessMessage('Player ID applied. Scan the QR code or open the URL to register.', {
                    theme: 'colored',
                    position: 'bottom-right',
                    autoClose: 2000,
                });
            })
            .catch((error) => {
                ToastMsgs.showErrorMessage('Failed to apply player ID', {
                    theme: 'colored',
                    position: 'bottom-right',
                    autoClose: 2000,
                });
                console.error('Error applying player ID:', error);
            });
    };

    const handleCloudUrlEdit = () => {
        setIsEditingCloudUrl(true);
    };

    const handleCloudUrlSave = async () => {
        try {
            await dispatch(postSetCloudUrl({ cloudUrl: cloudUrlInput })).unwrap();
            setIsEditingCloudUrl(false);
            ToastMsgs.showSuccessMessage('Cloud URL updated successfully', {
                theme: 'colored',
                position: 'bottom-right',
                autoClose: 2000,
            });
        } catch (error) {
            console.error('Error updating cloud URL:', error);
            ToastMsgs.showErrorMessage('Failed to update cloud URL', {
                theme: 'colored',
                position: 'bottom-right',
                autoClose: 2000,
            });
        }
    };

    const handleCloudUrlCancel = () => {
        setCloudUrlInput(cloudServiceUrl || '');
        setIsEditingCloudUrl(false);
    };

    const getPlayerRegistrationUrl = useMemo(() => {
        return (calcPlayerId: string) => {
            return `${cloudUrlInput || cloudServiceUrl}${API_ENDPOINTS.REGISTER_PLAYER}${calcPlayerId}`;
        };
    }, [cloudUrlInput, cloudServiceUrl]);

    const url = getPlayerRegistrationUrl(tempPlayerId.trim());

    return (
        <Box sx={{ p: 1 }}>
            {playerIdIsRegistered ? (
                <Typography variant="body2" sx={{ mb: 2 }} color="success.main">
                    Player ID is registered ✓
                </Typography>
            ) : (
                <Typography variant="body2" sx={{ mb: 2 }} color="error">
                    Player ID not registered yet
                </Typography>
            )}

            <Box sx={{ mb: 4 }}>
                <Typography variant="subtitle2" sx={{ mb: 1, color: 'text.secondary' }}>
                    Player ID
                </Typography>

                <Box sx={{ display: 'flex', flexDirection: 'row', gap: 2, mb: 2 }}>
                    <Box sx={{ flex: 1 }}>
                        <FormControlLabel
                            value="auto"
                            control={
                                <Radio
                                    checked={playerIdInputMode === 'auto'}
                                    onChange={handlePlayerIdModeChange}
                                />
                            }
                            label="Auto-generated Player ID"
                            sx={{ mb: 1 }}
                        />
                        <TextField
                            fullWidth
                            variant="outlined"
                            size="small"
                            placeholder="Auto-generated Player ID"
                            value={playerIdInputMode === 'auto' ? tempPlayerId : ''}
                            onChange={handlePlayerIdInputChange}
                            onBlur={handlePlayerIdBlur}
                            disabled={playerIdInputMode !== 'auto'}
                            InputProps={{ readOnly: true }}
                        />
                    </Box>

                    <Box sx={{ flex: 1 }}>
                        <FormControlLabel
                            value="manual"
                            control={
                                <Radio
                                    checked={playerIdInputMode === 'manual'}
                                    onChange={handlePlayerIdModeChange}
                                />
                            }
                            label="Manual Player ID"
                            sx={{ mb: 1 }}
                        />
                        <TextField
                            fullWidth
                            variant="outlined"
                            size="small"
                            placeholder="Enter Player ID manually"
                            value={playerIdInputMode === 'manual' ? tempPlayerId : ''}
                            onChange={handlePlayerIdInputChange}
                            onBlur={handlePlayerIdBlur}
                            disabled={playerIdInputMode !== 'manual'}
                        />
                    </Box>
                </Box>

                <Box sx={{ display: 'flex', gap: 2 }}>
                    {playerIdInputMode === 'auto' ? (
                        <Button
                            variant="contained"
                            size="small"
                            sx={{ minWidth: '80px' }}
                            onClick={handleGeneratePlayerId}
                        >
                            Generate
                        </Button>
                    ) : (
                        <Button
                            variant="contained"
                            size="small"
                            sx={{ minWidth: '80px' }}
                            onClick={handleApplyManualPlayerId}
                            disabled={!tempPlayerId.trim()}
                        >
                            Apply
                        </Button>
                    )}
                    <Button
                        variant="outlined"
                        size="small"
                        color="error"
                        sx={{ minWidth: '80px' }}
                        onClick={handleClearPlayerId}
                        disabled={!playerIdToken.trim() && !tempPlayerId.trim()}
                    >
                        Clear
                    </Button>
                </Box>

                <Typography variant="caption" sx={{ display: 'block', mt: 1, color: 'text.secondary' }}>
                    Auto-generate a Player ID, or enter one provided to you. Then scan the QR code or open the
                    URL on a logged-in device to register this player to your cloud account.
                </Typography>
            </Box>

            {tempPlayerId.trim() && (
                <Box sx={{ mb: 4 }}>
                    <Typography variant="subtitle2" sx={{ mb: 1, color: 'text.secondary' }}>
                        Registration QR Code
                    </Typography>
                    <Box
                        sx={{
                            width: '150px',
                            height: '150px',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            border: '1px solid #e0e0e0',
                            borderRadius: '4px',
                            padding: '8px',
                            bgcolor: 'background.paper',
                        }}
                    >
                        <QRCodeSVG
                            value={getPlayerRegistrationUrl(tempPlayerId.trim())}
                            size={134}
                            level="H"
                            includeMargin={false}
                        />
                    </Box>
                    <Typography
                        variant="caption"
                        sx={{ display: 'block', mt: 1, color: 'text.secondary' }}
                    >
                        URL:{' '}
                        {isElectron() ? (
                            <Link
                                component="button"
                                underline="hover"
                                sx={{ cursor: 'pointer', textAlign: 'left' }}
                                onClick={() => window.electronAPI?.openExternal(url)}
                            >
                                {url}
                            </Link>
                        ) : (
                            <Link
                                href={url}
                                target="_blank"
                                rel="noopener noreferrer"
                                underline="hover"
                                sx={{ cursor: 'pointer' }}
                            >
                                {url}
                            </Link>
                        )}
                        {!playerIdIsRegistered && ' (Not registered yet)'}
                    </Typography>
                </Box>
            )}

            {!hideCloudUrl && (
                <>
                    <Divider sx={{ my: 2 }} />

                    <Box sx={{ mb: 1 }}>
                        <Typography variant="subtitle1" sx={{ mb: 2 }}>
                            Cloud Service Configuration
                        </Typography>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                            <TextField
                                fullWidth
                                label="Cloud Service URL"
                                variant="outlined"
                                size="small"
                                value={cloudUrlInput}
                                onChange={(e) => setCloudUrlInput(e.target.value)}
                                disabled={!isEditingCloudUrl}
                                placeholder="Enter cloud service URL"
                            />
                            {!isEditingCloudUrl ? (
                                <Button variant="contained" size="small" onClick={handleCloudUrlEdit}>
                                    Edit
                                </Button>
                            ) : (
                                <>
                                    <Button variant="contained" size="small" onClick={handleCloudUrlSave}>
                                        Save
                                    </Button>
                                    <Button variant="outlined" size="small" onClick={handleCloudUrlCancel}>
                                        Cancel
                                    </Button>
                                </>
                            )}
                        </Box>
                    </Box>

                    <Divider sx={{ my: 2 }} />

                    <CloudPollingEditor />
                </>
            )}
        </Box>
    );
};
